name: "Blog of Wenli Zhang"
description: "Web Front-End Blog by Wenli Zhang"

url: "http://zhangwenli.com/blog"
loadingImg: "http://7xl1oi.com1.z0.glb.clouddn.com/loading.gif"
filePath: "http://7xl1oi.com1.z0.glb.clouddn.com/"

timezone: Asia/Shanghai

paginate: 20

highlighter: pygments

markdown: rdiscount
permalink: pretty
