name: "Blog of Wenli Zhang"
description: "Web Front-End Blog by Wenli Zhang"

url: "http://zhangwenli.com/blog"

timezone: Asia/Shanghai

paginate: 10

pygments: true

markdown: rdiscount
permalink: pretty
